# Generated by Django 6.0.2 on 2026-03-29 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_bankaccount_paypalaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='paypalaccount',
            name='is_default',
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paypalaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
