# Generated by Django 6.0.2 on 2026-02-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='account_set', related_query_name='account', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='account_set', related_query_name='account', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
