# Generated by Django 6.0.2 on 2026-03-11 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='username',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='useraccount',
            index=models.Index(fields=['username'], name='accounts_us_usernam_168046_idx'),
        ),
    ]
