# Generated by Django 6.0.2 on 2026-03-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_useraccount_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='two_factor_method',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('sms', 'SMS'), ('both', 'Email + SMS')], max_length=10, null=True),
        ),
    ]
