# Generated by Django 6.0.2 on 2026-05-13 22:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_useraccount_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('kyc', 'KYC Specialist')], default='kyc', max_length=10)),
                ('token', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('is_accepted', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='useraccount',
            name='resolved_issues_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('kyc', 'KYC Specialist')], default='user', max_length=10),
        ),
    ]
