# Generated by Django 6.0.2 on 2026-05-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_invitation_useraccount_resolved_issues_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('kyc', 'KYC Specialist'), ('affiliate', 'Affiliate')], default='kyc', max_length=10),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('kyc', 'KYC Specialist'), ('affiliate', 'Affiliate')], default='user', max_length=10),
        ),
    ]
