# Generated by Django 6.0.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_usersubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='auth_provider',
            field=models.CharField(
                choices=[('email', 'Email'), ('google', 'Google'), ('apple', 'Apple')],
                default='email',
                max_length=20,
            ),
        ),
    ]
