# Generated by Django 6.0.2 on 2026-09-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_useraccount_auth_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='plan',
            field=models.CharField(choices=[('monthly', 'Monthly ($2/mo)'), ('yearly', 'Yearly ($12/yr)'), ('single', 'Single-Use Pass ($10)')], max_length=15),
        ),
    ]
