# Generated by Django 6.0.2 on 2026-05-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralprofile',
            name='referred_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
