# Generated by Django 6.0.2 on 2026-03-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excrow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrow',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='escrow',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
