# Generated by Django 6.0.2 on 2026-03-12 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excrow', '0003_escrow_order_id'),
    ]

    operations = [
    ]
