# Generated by Django 6.0.2 on 2026-03-12 22:05

import app.excrow.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excrow', '0004_auto_20260312_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrow',
            name='order_id',
            field=models.CharField(db_index=True, default=app.excrow.models.generate_order_id, editable=False, max_length=20, unique=True),
        ),
    ]
