# Generated by Django 6.0.2 on 2026-03-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excrow', '0005_alter_escrow_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrow',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('funded', 'Funded'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('under_review', 'Under Review'), ('issue_raised', 'Issue Raised'), ('return_in_progress', 'Return In Progress'), ('resolved', 'Resolved'), ('refunded', 'Refunded'), ('payment_released', 'Payment Released'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='created', max_length=20),
        ),
    ]
