# Generated by Django 6.0.2 on 2026-03-12 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excrow', '0006_alter_escrow_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('funded', 'Funded'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('under_review', 'Under Review'), ('issue_raised', 'Issue Raised'), ('return_in_progress', 'Return In Progress'), ('resolved', 'Resolved'), ('refunded', 'Refunded'), ('payment_released', 'Payment Released'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('escrow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='excrow.escrow')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
