# Generated by Django 6.0.2 on 2026-03-14 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excrow', '0007_escrowstatushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowinstallment',
            name='is_paid',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='escrowinstallment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escrowinstallment',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
