# Generated by Django 6.0.2 on 2026-05-17 20:15

import cloudinary.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excrow', '0009_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrow',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('funded', 'Funded'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('under_review', 'Under Review'), ('issue_raised', 'Issue Raised'), ('dispute_in_progress', 'Dispute In Progress'), ('return_in_progress', 'Return In Progress'), ('resolved', 'Resolved'), ('refunded', 'Refunded'), ('payment_released', 'Payment Released'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='created', max_length=20),
        ),
        migrations.AlterField(
            model_name='escrowstatushistory',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('funded', 'Funded'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('under_review', 'Under Review'), ('issue_raised', 'Issue Raised'), ('dispute_in_progress', 'Dispute In Progress'), ('return_in_progress', 'Return In Progress'), ('resolved', 'Resolved'), ('refunded', 'Refunded'), ('payment_released', 'Payment Released'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20),
        ),
        migrations.CreateModel(
            name='EscrowDispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('Fake product', 'Fake product'), ('Color not correct', 'Color not correct'), ('Broken', 'Broken'), ('Not working', 'Not working'), ('Others', 'Others')], max_length=50)),
                ('note', models.TextField()),
                ('escrow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='excrow.escrow')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raised_disputes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EscrowDisputeImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='excrow.escrowdispute')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
