# Generated by Django 6.0.2 on 2026-05-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excrow', '0010_alter_escrow_status_alter_escrowstatushistory_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowdispute',
            name='decision_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escrowdispute',
            name='status',
            field=models.CharField(choices=[('pending', 'AI is checking'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
    ]
