# Generated by Django 6.0.2 on 2026-05-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excrow', '0011_escrowdispute_decision_reason_escrowdispute_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrowdispute',
            name='status',
            field=models.CharField(choices=[('pending_ai', 'AI is checking'), ('pending_kyc', 'KYC Resolver checking'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('resolved', 'Resolved')], default='pending_ai', max_length=20),
        ),
    ]
