# Generated by Django 6.0.2 on 2026-05-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excrow', '0012_alter_escrowdispute_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowdispute',
            name='ai_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escrowdispute',
            name='ai_decision',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='escrowdispute',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
