# Generated by Django 6.0.2 on 2026-05-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excrow', '0013_escrowdispute_ai_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowdispute',
            name='penalty_charged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='escrowdispute',
            name='seller_response',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='escrowdispute',
            name='seller_response_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='escrowdispute',
            name='status',
            field=models.CharField(choices=[('pending_ai', 'AI is checking'), ('awaiting_seller', 'Awaiting Seller Response'), ('pending_kyc', 'KYC Resolver checking'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('resolved', 'Resolved')], default='pending_ai', max_length=20),
        ),
    ]
