# Generated by Django 6.0.2 on 2026-05-19 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excrow', '0016_escrowrating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrowrating',
            name='escrow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='excrow.escrow'),
        ),
        migrations.AlterUniqueTogether(
            name='escrowrating',
            unique_together={('escrow', 'rated_by')},
        ),
    ]
