# Generated by Django 6.0.2 on 2026-05-21 21:18

import cloudinary.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excrow', '0017_alter_escrowrating_escrow_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowDeliveryProof',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', cloudinary.models.CloudinaryField(max_length=255)),
                ('escrow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_proofs', to='excrow.escrow')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
