# Generated by Django 6.0.2 on 2026-05-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excrow', '0018_escrowdeliveryproof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrow',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('funded', 'Funded'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('under_review', 'Under Review'), ('issue_raised', 'Issue Raised'), ('dispute_in_progress', 'Dispute In Progress'), ('return_in_progress', 'Return In Progress'), ('resolved', 'Resolved'), ('dispute_resolved', 'Dispute Resolved'), ('refunded', 'Refunded'), ('payment_released', 'Payment Released'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='created', max_length=20),
        ),
        migrations.AlterField(
            model_name='escrowstatushistory',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('funded', 'Funded'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('under_review', 'Under Review'), ('issue_raised', 'Issue Raised'), ('dispute_in_progress', 'Dispute In Progress'), ('return_in_progress', 'Return In Progress'), ('resolved', 'Resolved'), ('dispute_resolved', 'Dispute Resolved'), ('refunded', 'Refunded'), ('payment_released', 'Payment Released'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20),
        ),
    ]
