# Generated by Django 6.0.2 on 2026-03-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeconfiguration',
            name='stripe_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feeconfiguration',
            name='stripe_fixed_fee',
            field=models.DecimalField(decimal_places=2, default=1.2, max_digits=6),
            preserve_default=False,
        ),
    ]
