# Generated by Django 6.0.2 on 2026-03-29 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_feeconfiguration_stripe_fee_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeconfiguration',
            name='withdraw_fee',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feeconfiguration',
            name='withdraw_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
