# Generated by Django 6.0.2 on 2026-04-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_feeconfiguration_withdraw_fee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feeconfiguration',
            options={'verbose_name': 'Fee Configuration', 'verbose_name_plural': 'Fee Configurations'},
        ),
        migrations.AddField(
            model_name='feeconfiguration',
            name='withdraw_min_amount',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Minimum amount a user can request to withdraw.', max_digits=10),
        ),
    ]
