# Generated by Django 6.0.2 on 2026-05-23 20:21

import cloudinary.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_alter_feeconfiguration_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingBanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, help_text='Optional banner title', max_length=255, null=True)),
                ('image', cloudinary.models.CloudinaryField(help_text='Cloudinary image upload for marketing banner', max_length=255)),
                ('link', models.URLField(blank=True, help_text='Link to open when banner is clicked', max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Marketing Banner',
                'verbose_name_plural': 'Marketing Banners',
                'ordering': ['-created_at'],
            },
        ),
    ]
