# Generated by Django 6.0.2 on 2026-05-20 19:15

import app.affiliate.models
import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('excrow', '0017_alter_escrowrating_escrow_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateGlobalBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_cap', models.DecimalField(decimal_places=2, default=Decimal('500000.00'), help_text='MXN', max_digits=16)),
                ('current_month_spend', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='MXN spent this month', max_digits=16)),
                ('cap_year', models.PositiveSmallIntegerField(default=2025)),
                ('cap_month', models.PositiveSmallIntegerField(default=1)),
                ('rewards_paused', models.BooleanField(default=False, help_text='Manually pause new reward generation')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Affiliate Global Budget',
            },
        ),
        migrations.CreateModel(
            name='AffiliateApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('discord', 'Discord'), ('both', 'Both')], max_length=10)),
                ('community_name', models.CharField(help_text='e.g. SNEAKERHEADS_MX', max_length=200)),
                ('community_url', models.URLField(help_text='Invite link or public profile URL')),
                ('community_member_count', models.PositiveIntegerField(default=0)),
                ('community_description', models.TextField(blank=True)),
                ('desired_slug', models.CharField(blank=True, help_text="Applicant's preferred slug, subject to admin approval", max_length=80)),
                ('tax_id', models.CharField(blank=True, help_text='RFC / Business Number', max_length=50)),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(default='MX', max_length=80)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('clabe', models.CharField(blank=True, help_text='18-digit CLABE for SPEI', max_length=18)),
                ('account_holder_name', models.CharField(blank=True, max_length=200)),
                ('id_document', cloudinary.models.CloudinaryField(blank=True, help_text='Government-issued ID', max_length=255, null=True)),
                ('tax_document', cloudinary.models.CloudinaryField(blank=True, help_text='Tax certificate / RFC document', max_length=255, null=True)),
                ('bank_statement', cloudinary.models.CloudinaryField(blank=True, help_text='Recent bank statement', max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], db_index=True, default='pending', max_length=15)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_affiliate_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, help_text='Set when the application is created by an existing user. May be null for pre-creation applications.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AffiliateNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='affiliate.affiliateapplication')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AffiliateProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affiliate_id', models.CharField(db_index=True, default=app.affiliate.models.generate_affiliate_id, max_length=20, unique=True)),
                ('slug', models.SlugField(help_text='Vanity slug: payparo.com/p/<slug>', max_length=80, unique=True)),
                ('tier', models.CharField(choices=[('base', 'Base (30%)'), ('elevated', 'Elevated (40%)')], default='base', max_length=10)),
                ('total_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_pending_hold', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_released', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_paid_out', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('withdrawable_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='affiliate.affiliateapplication')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AffiliateFraudFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signal_type', models.CharField(choices=[('self_referral', 'Self Referral'), ('same_ip', 'Same IP Address'), ('same_device', 'Same Device Fingerprint'), ('same_gov_id', 'Same Government ID'), ('same_bank', 'Same Bank Account (CLABE)'), ('wash_trading', 'Wash Trading')], max_length=20)),
                ('detail', models.TextField(blank=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('attributed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_flags_as_user', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_fraud_flags', to=settings.AUTH_USER_MODEL)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_flags', to='affiliate.affiliateprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AffiliateClick',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_fingerprint', models.CharField(blank=True, db_index=True, max_length=128)),
                ('clicked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('converted', models.BooleanField(default=False, help_text='True after the visitor signs up')),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='affiliate.affiliateprofile')),
            ],
            options={
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='AffiliateAttribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_transaction_discount_used', models.BooleanField(default=False)),
                ('first_transaction_discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('activation_bonus_paid', models.BooleanField(default=False, help_text='200 MXN one-time bonus paid to affiliate')),
                ('fraud_flagged', models.BooleanField(default=False)),
                ('referred_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_attribution', to=settings.AUTH_USER_MODEL)),
                ('click', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='affiliate.affiliateclick')),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='affiliate.affiliateprofile')),
            ],
            options={
                'ordering': ['-attributed_at'],
            },
        ),
        migrations.CreateModel(
            name='AffiliateReward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reward_type', models.CharField(choices=[('recurring_commission', 'Recurring Commission'), ('activation_bonus', 'Activation Bonus (200 MXN)'), ('deduction', 'Post-Payout Deduction')], max_length=25)),
                ('state', models.CharField(choices=[('pending_hold', 'Pending Hold (14 days)'), ('released', 'Released'), ('voided', 'Voided'), ('deducted', 'Deducted')], db_index=True, default='pending_hold', max_length=15)),
                ('currency', models.CharField(default='MXN', max_length=5)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('commission_rate', models.DecimalField(decimal_places=4, default=Decimal('0.30'), max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('hold_until', models.DateTimeField(blank=True, help_text='When pending_hold expires and reward is released', null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=100, unique=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='affiliate.affiliateprofile')),
                ('attribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards', to='affiliate.affiliateattribution')),
                ('escrow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliate_rewards', to='excrow.escrow')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AffiliateTierHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('monthly_volume', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('tier_applied', models.CharField(choices=[('base', 'Base (30%)'), ('elevated', 'Elevated (40%)')], max_length=10)),
                ('commission_rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_history', to='affiliate.affiliateprofile')),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='AffiliateWithdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='MXN', max_length=5)),
                ('bank_name', models.CharField(max_length=100)),
                ('clabe', models.CharField(max_length=18)),
                ('account_holder_name', models.CharField(max_length=200)),
                ('cfdi_invoice', cloudinary.models.CloudinaryField(blank=True, help_text='CFDI invoice PDF', max_length=255, null=True)),
                ('cfdi_invoice_number', models.CharField(blank=True, max_length=100)),
                ('isr_withholding', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=15)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('transaction_ref', models.CharField(blank=True, help_text='SPEI transaction reference', max_length=100)),
                ('admin_notes', models.TextField(blank=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='affiliate.affiliateprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_affiliate_withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='affiliateapplication',
            index=models.Index(fields=['status'], name='affiliate_a_status_155ae2_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliateapplication',
            index=models.Index(fields=['email'], name='affiliate_a_email_006862_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliateprofile',
            index=models.Index(fields=['slug'], name='affiliate_a_slug_a4f131_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliateprofile',
            index=models.Index(fields=['affiliate_id'], name='affiliate_a_affilia_3f70f0_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliatefraudflag',
            index=models.Index(fields=['affiliate', 'resolved'], name='affiliate_a_affilia_08cbcc_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliateclick',
            index=models.Index(fields=['affiliate', 'clicked_at'], name='affiliate_a_affilia_bad48b_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliateclick',
            index=models.Index(fields=['device_fingerprint'], name='affiliate_a_device__d4fc43_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliateattribution',
            index=models.Index(fields=['affiliate'], name='affiliate_a_affilia_899339_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliateattribution',
            index=models.Index(fields=['referred_user'], name='affiliate_a_referre_d84fbd_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliatereward',
            index=models.Index(fields=['affiliate', 'state'], name='affiliate_a_affilia_7dcfb5_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliatereward',
            index=models.Index(fields=['escrow'], name='affiliate_a_escrow__ca9f64_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliatereward',
            index=models.Index(fields=['hold_until'], name='affiliate_a_hold_un_f62338_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='affiliatetierhistory',
            unique_together={('affiliate', 'year', 'month')},
        ),
        migrations.AddIndex(
            model_name='affiliatewithdrawal',
            index=models.Index(fields=['affiliate', 'status'], name='affiliate_a_affilia_ecc204_idx'),
        ),
    ]
