# Generated by Django 6.0.2 on 2026-05-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateapplication',
            name='password_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
