from django.urls import path
from .views import (
    EscrowListCreateView, 
    EscrowDetailView, 
    UserSearchView,
    OrderHistory,
    OrderHistoryDetailView,
    EscrowAcceptView,
    EscrowSendProductView,
    EscrowDeliveredView,
    EscrowDisputeView,
    DisputeListView,
    RecentEscrowsView,
    SellerDisputeResponseView,
    KYCDisputeResolveView,
    KYCDisputeListView,
    KYCDisputeAssignView,
)

urlpatterns = [
    path("search/", UserSearchView.as_view(), name="user-search"),
    path("", EscrowListCreateView.as_view(), name="escrow-list-create"),
    path("<uuid:pk>/", EscrowDetailView.as_view(), name="escrow-detail"),
    path("<uuid:pk>/accept/", EscrowAcceptView.as_view(), name="escrow-accept"),
    path("<uuid:pk>/send-product/", EscrowSendProductView.as_view(), name="escrow-send-product"),
    path("<uuid:pk>/delivered/", EscrowDeliveredView.as_view(), name="escrow-delivered"),
    path("<uuid:pk>/dispute/", EscrowDisputeView.as_view(), name="escrow-dispute"),
    path("order-history/", OrderHistory.as_view(), name="order-history"),
    path("order-history/<uuid:pk>/", OrderHistoryDetailView.as_view(), name="order-history-detail"),
    path("recent/", RecentEscrowsView.as_view(), name="recent-escrows"),
    path("disputes/", DisputeListView.as_view(), name="escrow-disputes"),
    path("disputes/<uuid:pk>/seller-response/", SellerDisputeResponseView.as_view(), name="dispute-seller-response"),
    path('disputes/unassigned/', KYCDisputeListView.as_view(), name='dispute-list-kyc'),
    path('disputes/<uuid:pk>/assign/', KYCDisputeAssignView.as_view(), name='dispute-assign-kyc'),
    path("disputes/<uuid:pk>/kyc-resolve/", KYCDisputeResolveView.as_view(), name="dispute-kyc-resolve"),
]
